import { Inter, Roboto, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar';
import Hero from "../components/Hero";
import { GeistSans } from 'geist/font/sans';

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const roboto = Roboto({ subsets: ["latin"], weight: '300', variable: '--font-roboto' });
const poppins = Poppins({ subsets: ["latin"], weight: '300', variable: '--font-poppins' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} ${poppins.variable} ${GeistSans.variable}`}>
        <Navbar />
        
        {children}
        
      </body>
    </html>
  );
}
